### ISSUE TITLE
GlobAsyncRef flush via container.flush() does not work

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#365]
According to the documentation of `GlobAsyncRef` it is possible use `container.flush()` to publish all changes. However this does unfortunately not work:

```cpp
dash::Array<int> data(dash::size());
*(array.lbegin()) = 0;
array.barrier();

mutex.lock();
int tmp = array.async[0];
arrary.async[0] = tmp + 1;
array.flush(); // using gref.flush() works
mutex.unlock();
array.barrier();
// postcondition: array[0] == dash::size();
```

This has to be investigated further. My guess is that the problem is the value comparison in the assignment operator. Furthermore the async stuff is not threadsafe in any case.

Maybe we should document this as a known limitation in 0.3.0, as fixing this seems quite elaborate.

**Comment by devreal** [comment]
> `arrary.async[dash::myid()] = tmp + 1;`

Shouldn't this be 
```
arrary.async[0] = tmp + 1;
            ^^^
```
?

The following (adapted) test succeeds:

```
  dash::Array<int> array(dash::size());
  *(array.lbegin()) = 0;
  array.barrier();

  dash::Mutex mutex;

  mutex.lock();
  int tmp = array.async[0];
  array.async[0] = tmp + 1;
  array.flush(); // using gref.flush() works
  mutex.unlock();
  array.barrier();

  // postcondition: array[0] == dash::size();
  ASSERT_EQ_U(dash::size(), array[0]);
```

> Furthermore the async stuff is not threadsafe in any case.

Mhh, as long as two threads do not share a `GlobAsyncRef` object it is thread-safe. Of course, you get race-conditions if two threads write to the same global memory through different references but that is not in our hands. What exactly do you have in mind?

The general problem is that the `GlobAsyncRef` is decoupled from the container so a flush will not force an update on pending async references, they become stale without anyone noticing. That should be documented, yes.

**Comment by fmoessbauer** [comment]
You are right with `^^^` ;) Have you tried with nastympi? I first had the errors in CI and then was only able to generate them using nastympi.

**Comment by devreal** [comment]
NastyMPI dies with a Segfault on my machine: 

```
[----------] 53 tests will be run.
[----------] run 1 out of 5 tests from GlobAsyncRefTest
[  RUN     ] GlobAsyncRefTest.ContainerFlush
[= -1 LOG =]       GlobAsyncRefTest.h :  13 | >>> Test suite: GlobAsyncRefTest 
[= -1 LOG =]               TestBase.h : 251 | ===> Running test case GlobAsyncRefTest.ContainerFlush ... 
[=  0 LOG =]               TestBase.h : 254 | -==- DASH initialized with 2 units 

Thread 1 "dash-test-mpi" received signal SIGSEGV, Segmentation fault.
nasty_win_get_info (win=win@entry=0xbaf500) at src/nasty_runtime/win_storage.c:158
158       return info;
(gdb) bt
#0  nasty_win_get_info (win=win@entry=0xbaf500) at src/nasty_runtime/win_storage.c:158
#1  0x00007ffff7bd3be3 in nasty_mpi_execute_cached_calls (win=win@entry=0xbaf500, target_rank=target_rank@entry=-123, mayFlush=mayFlush@entry=false) at src/nasty_runtime/runtime.c:307
#2  0x00007ffff7bd4420 in MPI_Win_flush_all (win=0xbaf500) at src/nasty_mpi.c:161
#3  0x00000000007994bc in dart_flush_all ()
#4  0x00000000006a4632 in GlobAsyncRefTest_ContainerFlush_Test::TestBody() ()
#5  0x000000000076572d in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#6  0x000000000075ed31 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#7  0x0000000000742506 in testing::Test::Run() ()
#8  0x0000000000742e9e in testing::TestInfo::Run() ()
#9  0x0000000000743591 in testing::TestCase::Run() ()
#10 0x000000000074a6d8 in testing::internal::UnitTestImpl::RunAllTests() ()
#11 0x0000000000766d05 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#12 0x000000000075fb73 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#13 0x0000000000749174 in testing::UnitTest::Run() ()
#14 0x00000000004ebaeb in main ()
```

@rkowalewski ?
